server:
  port: 8080

spring:
  application:
    name: AUTH-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  cloud:
    config:
      import-check:
        enabled: false

jwt:
  secret: ${SECRET_KEY}

admin-paths:
  paths:
    -
      uri: "/usuarios/nuevo"
      method: "POST"
    -
      uri: "/usuarios/auxiliares"
      method: "GET"